# name              lanes                               alias           speed       index   mtu      fec
Ethernet0           2                                   Port0           25000       0       9126     rs
Ethernet1           1                                   Port1           25000       1       9126     rs
Ethernet2           0                                   Port2           25000       2       9126     rs
Ethernet3           6                                   Port3           25000       3       9126     rs
Ethernet4           3                                   Port4           25000       4       9126     rs
Ethernet5           7                                   Port5           25000       5       9126     rs
Ethernet6           4                                   Port6           25000       6       9126     rs
Ethernet7           8                                   Port7           25000       7       9126     rs
Ethernet8           11                                  Port8           25000       8       9126     rs
Ethernet9           5                                   Port9           25000       9       9126     rs
Ethernet10          12                                  Port10          25000       10      9126     rs
Ethernet11          10                                  Port11          25000       11      9126     rs
Ethernet12          13                                  Port12          25000       12      9126     rs
Ethernet13          9                                   Port13          25000       13      9126     rs
Ethernet14          17                                  Port14          25000       14      9126     rs
Ethernet15          14                                  Port15          25000       15      9126     rs
Ethernet16          19                                  Port16          25000       16      9126     rs
Ethernet17          15                                  Port17          25000       17      9126     rs
Ethernet18          21                                  Port18          25000       18      9126     rs
Ethernet19          16                                  Port19          25000       19      9126     rs
Ethernet20          23                                  Port20          25000       20      9126     rs
Ethernet21          18                                  Port21          25000       21      9126     rs
Ethernet22          26                                  Port22          25000       22      9126     rs
Ethernet23          20                                  Port23          25000       23      9126     rs
Ethernet24          28                                  Port24          25000       24      9126     rs
Ethernet25          22                                  Port25          25000       25      9126     rs
Ethernet26          30                                  Port26          25000       26      9126     rs
Ethernet27          25                                  Port27          25000       27      9126     rs
Ethernet28          32                                  Port28          25000       28      9126     rs
Ethernet29          24                                  Port29          25000       29      9126     rs
Ethernet30          34                                  Port30          25000       30      9126     rs
Ethernet31          27                                  Port31          25000       31      9126     rs
Ethernet32          36                                  Port32          25000       32      9126     rs
Ethernet33          29                                  Port33          25000       33      9126     rs
Ethernet34          38                                  Port34          25000       34      9126     rs
Ethernet35          31                                  Port35          25000       35      9126     rs
Ethernet36          39                                  Port36          25000       36      9126     rs
Ethernet37          33                                  Port37          25000       37      9126     rs
Ethernet38          40                                  Port38          25000       38      9126     rs
Ethernet39          35                                  Port39          25000       39      9126     rs
Ethernet40          41                                  Port40          25000       40      9126     rs
Ethernet41          37                                  Port41          25000       41      9126     rs
Ethernet42          43                                  Port42          25000       42      9126     rs
Ethernet43          42                                  Port43          25000       43      9126     rs
Ethernet44          45                                  Port44          25000       44      9126     rs
Ethernet45          44                                  Port45          25000       45      9126     rs
Ethernet46          47                                  Port46          25000       46      9126     rs
Ethernet47          46                                  Port47          25000       47      9126     rs
Ethernet48          55,54,52,53                         Port48          100000      48      9126     rs
Ethernet52          48,51,50,49                         Port49          100000      49      9126     rs
Ethernet56          63,61,62,60                         Port50          100000      50      9126     rs
Ethernet60          56,58,57,59                         Port51          100000      51      9126     rs
Ethernet64          69,68,71,70                         Port52          100000      52      9126     rs
Ethernet68          66,67,64,65                         Port53          100000      53      9126     rs
Ethernet72          76,78,79,77                         Port54          100000      54      9126     rs
Ethernet76          75,72,73,74                         Port55          100000      55      9126     rs
Ethernet80           80                                 Port56           25000      56      9126     rs 
Ethernet81           81                                 port57           25000      57      9126     rs 
